### ISSUE TITLE
Unable to display to Discord

### ISSUE THREAD

**Issue by Candy-Sama** [KazeJiyu/eclipse-discord-integration#94] opened 2021-05-24 06:43 UTC
Hi there!

I've installed the plugin, but it doesn't show up on discord - even after a restart of both applications. What could I do?

Steps to replicate:

- Drag and drop button into Eclipse workspace
- Install
- Restart Eclipse and Discord

Solutions tried:
- Launched Discord permanently in Admin Mode (Currently running Discord in Admin Mode rn)
- Reinstalled the plugin
- Restarted Eclipse 
- Restarted Discord
- Restarted Eclipse and Discord
- Restarted PC

I don't know what else I could try, please help!

**Comment by echebbi** [comment] 2021-07-09 08:40
Hi, I apologize for the (very) late answer. Have you tried to manually tell Discord to detect Eclipse IDE as a game?

1. Open Discord's `User Settings`
2. Go the `Activity Status` tab
3. Click on the `Add it!` button
3. Select _Eclipse IDE_

**Comment by Candy-Sama** [comment] 2021-07-09 10:08
Hi there, no worries!

I've resolved to not just install it anymore, I'm sorry.

But for future reference, yes, I have :3

Thanks for reading and stay safe!

**Comment by echebbi** [comment] 2021-07-09 12:49
Ahah no problem. Thank you for the feedback, as I can't reproduce the problem I'll close the issue for now.

**Closed as completed by echebbi** 2021-07-09 12:49 UTC
